
security:
  jwt:
    public-key: classpath:public.txt
server:
  port: 8080

zuul:
  sensitiveHeaders:
  routes:
    oauth:
      path: /oauth/**
      url: ${API_OAUTH_ADDRESS:http://localhost:8081/oauth}
    processo-industrial:
      path: /processoindustrial/**
      url: ${API_PROCESSO_INDUSTRIAL_ADDRESS:http://localhost:8082/api}
    consultorias-assessorias:
      path: /consultoriasassessorias/**
      url: ${API_CONSULTORIAS_ASSESSORIAS_ADDRESS:http://localhost:8084/api}
    normas:
      path: /normas/**
      url: ${API_NORMAS_ADDRESS:http://localhost:8085/api}
spring:
  rabbitmq:
    host: ${RABBIT_ADDRESS:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}

