
security:
  jwt:
    public-key: classpath:public.txt
server:
  port: 8080

zuul:
  sensitiveHeaders:
  routes:
    oauth:
      path: /oauth/**
      url: http://tcc-auth-api-service.default.svc.cluster.local:8080/oauth
    processo-industrial:
      path: /processoindustrial/**
      url: http://tcc-proc-ind-api-service.default.svc.cluster.local:8080/api