
security:
  jwt:
    public-key: classpath:public.txt
server:
  port: 8080

zuul:
  sensitiveHeaders:
  routes:
    oauth:
      path: /oauth/**
      url: ${API_OAUTH_ADDRESS:'http://localhost:8083/oauth'}
    processo-industrial:
      path: /processoindustrial/**
      url: ${API_PROCESSO_INDUSTRIAL_ADDRESS:'http://localhost:8081/api'}
spring:
  rabbitmq:
    host: ${RABBIT_ADDRESS:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}

